### ISSUE TITLE
Update the supported Engines section

### ISSUE THREAD

**Issue by vinijaiswal** [unitycatalog/unitycatalog#1]
In the current architecture slide under the docs section, can we please add Apache Spark, Presto and Trino as the supported engines. Thank you!

**Comment by Jaydeep10** [comment]
Hi VinSure. Please add meRegards JaySent from my iPhoneOn Jun 13, 2024, at 9:48 AM, Vini Jaiswal ***@***.***> wrote:﻿
In the current architecture slide under the docs section, can we please add Apache Spark, Presto and Trino as the supported engines. Thank you!

**Comment by vinijaiswal** [comment]
I need access to the writable version of the diagram. If we have raw files, I can make the required changes. Thank you!!!

**Comment by vinijaiswal** [comment]
I was able to update it and created a PR: https://github.com/unitycatalog/unitycatalog/pull/39

Thank you!!
