### ISSUE TITLE
Row Filter limitations in UC

### ISSUE THREAD

**Issue by ShashiatShell** [unitycatalog/unitycatalog#108]
**Is your feature request related to a problem? Please describe.**

**I would like Row Filter to work with Merge load type as well**

**Additional context**

**Comment by MrPowers** [comment]
@ShashiatShell, could you add some additional detail, possibly with a code snippet, so I can understand this suggestion better? Thank you very much!

**Comment by ShashiatShell** [comment]
@MrPowers Thanks for checking this. This is with regards to the below limitation mentioned in the databricks documentation, that 
MERGE statements do not support tables with row filter policies that contain nesting, aggregations, windows, limits, or non-deterministic functions. In my databricks notebooks, we always load the data to the delta lake tables using MERGE statements and with that we are unable to apply RLS Filter. hence wanted to understand how shall we apply RLS Filter for such use case or any alternatives. I would like to avoid creating RLS enabled views. Hope this helps. 

https://docs.databricks.com/en/tables/row-and-column-filters.html
![image](https://github.com/unitycatalog/unitycatalog/assets/87582148/0ff8286c-18cb-4610-a1a3-25e1afd98f00)

**Comment by kulte** [comment]
OSS UC (this project) doesn't have row filters at all. You are asking about a limitation of Databricks UC.

**Comment by MrPowers** [comment]
@ShashiatShell - thanks for clarifying.  The issues on this repo are for the Unity Catalog open source project.  Can you please ask this question on community.databricks.com?  Thank you!
