### ISSUE TITLE
Give UC docs virtual environment a better name

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#111]
Here are the current README instructions:

```
python -m venv venv
. ./venv/bin/activate 
```

We should give the virtual environment a better name.  Something like `uc_docs_venv` or whatever is conventional.

We should also add more instructions on how to use the virtual environment at a later date, how to update it, etc.

**Comment by asingamaneni** [comment]
I can pick this issue

**Comment by MrPowers** [comment]
@asingamaneni - sorry, someone already grabbed this one: https://github.com/unitycatalog/unitycatalog/pull/117

I should have assigned them on this issue, my fault.

**Comment by MrPowers** [comment]
Oh, actually I can't assign them cause @arslanaka hasn't commented here yet.

**Comment by MrPowers** [comment]
Thanks @arslanaka - assigned this one to you!
