### ISSUE TITLE
bin/start-uc-server: Error: Could not find or load main class io.unitycatalog.server.UnityCatalogServer

### ISSUE THREAD

**Issue by havryliuk** [unitycatalog/unitycatalog#120]
**Describe the bug**

UC server cannot be started with `start-uc-server`

**To Reproduce**

1. git clone
2. build/sbt package
3. bin/start-uc-server

**Expected behavior**

The server should start as described in README

**System [please complete the following information]:**

-   OS: Windows 11 Enterprise - Version	10.0.22631 Build 22631

**Additional context**

Same behaviour when checking out, building and trying to run the server in Intellij IDEA.
Tried separately in a new folder with just command line (Git Bash)

![image](https://github.com/unitycatalog/unitycatalog/assets/1567804/cde2df35-d2a9-4eaa-8afc-9cada3eb592e)

**Comment by filipovskid** [comment]
I was facing the same issue setting up the project on Windows. The issue is with the generated classpath. I can take this up.
