### ISSUE TITLE
Auto assign issues with take comment

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#121]
Users should be able to comment "take" on an issue to be auto-assigned the issue.

This creates a good experience for OSS users.  They can grab an issue and it will make sure nobody else is working on it.

This PR shows how to add this functionality: https://github.com/delta-io/delta-rs/pull/1851

**Comment by asingamaneni** [comment]
I can take this if it's not picked yet

**Comment by MrPowers** [comment]
Thanks @asingamaneni - assigned this one to you!

**Comment by filipovskid** [comment]
Hello @asingamaneni, can you provide an update on this issue? It would be really nice to have it. Thank you for your contribution!

**Comment by nijanthanvijayakumar** [comment]
Hi @filipovskid and @MrPowers - I have opened a PR on this topic. Hope it's okay.

**Comment by asingamaneni** [comment]
> Hello @asingamaneni, can you provide an update on this issue? It would be really nice to have it. Thank you for your contribution!

Sorry I was on vacation last week and couldn't access laptop!
