### ISSUE TITLE
Compile project failed: @javax.annotation.Generated cannot find symbol

### ISSUE THREAD

**Issue by georgehu0815** [unitycatalog/unitycatalog#15]
Compile the project using `build/sbt package`
**JDK:**
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
env:
WSL, Ubuntu 22

[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/ListFunctionsResponse.java:37:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/ListSchemasResponse.java:37:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/SchemaInfo.java:41:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/ListTablesResponse.java:37:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/TableInfo.java:51:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/ListVolumesResponseContent.java:37:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/VolumeInfo.java:42:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/UpdateCatalog.java:36:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/UpdateSchema.java:36:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] /mnt/a/work/unitycatalog/server/src/main/java/io/unitycatalog/server/model/UpdateVolumeRequestContent.java:33:1: cannot find symbol
[error]   symbol:   class Generated
[error]   location: package javax.annotation
[error] javax.annotation.Generated
[error] (server / Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 14 s, completed Jun 13, 2024, 5:05:50 PM

**Comment by georgehu0815** [comment]
https://stackoverflow.com/questions/64809111/sbt-server-is-already-booting-error-when-launching-sbt-from-wsl2-ubuntu

**Comment by ray-harrison** [comment]
FYI, as noted in another open issue, the solution for another person and for me was to change all references of  javax.annotation.Generated to javax.annotation.processing.Generated.

**Comment by filipovskid** [comment]
This was resolved with #19. It should be okay for closing @MrPowers

**Comment by MrPowers** [comment]
Ok, closing, thanks for the ping @filipovskid
