### ISSUE TITLE
Add duckdb tutorial instructions to the tutorial test script

### ISSUE THREAD

**Issue by tdas** [unitycatalog/unitycatalog#150]
**Is your feature request related to a problem? Please describe.**

In our [README](https://github.com/unitycatalog/unitycatalog/tree/main?tab=readme-ov-file#operate-on-delta-tables-with-duckdb), we have instructions on how to use UC OSS with DuckDB. 

However, our [tutorial test script](https://github.com/unitycatalog/unitycatalog/blob/main/tests/test_tutorial.py) does not cover DuckDB.

So we should add DuckDB to the tests to make sure our README instructions never break.

**Describe the solution you would like**
I think there are 2 options of how to test it out. 
- Either test using shell scripts (like what the rest of the test script does).
- Or, using python directly by `pip install duckdb` and then running all the duckdb command via python.

**Additional context**

Github actions test the test scripts, so the goal is to make sure those tests pass reliably with duckdb.

**Comment by vksx** [comment]
Hi @tdas I'll be happy to work on this issue.
