### ISSUE TITLE
Replace H2 db file by DDL-like expressions

### ISSUE THREAD

**Issue by SemyonSinchenko** [unitycatalog/unitycatalog#152]
**Is your feature request related to a problem? Please describe.**
Binary files do not support resolving of merge conflicts. It is also dangerous to run random binary from git.

**Describe the solution you would like**
Replace `etc/db/h2db.mv.db` file by DDL and a script that creates a file if it does not exist. For example, DDL may be implemented as a SQL files with `CREATE TABLE` statements and a script will be just a call to [H2 Tool RunScript](https://h2database.com/javadoc/org/h2/tools/RunScript.html).

**Additional context**
Security + Maintainability.

For example, [this PR](https://github.com/unitycatalog/unitycatalog/pull/151) is almost impossible to merge because conflict in a binary cannot be resolved. Opposite, SQL statements in DDL files will be just a text and may be easily validated by reviewer and merge conflict won't be a problem anymore.

And it is very dangerous and insecure to distribute a binary file. Anyone can ingest anything to it and there are no automatic checkers of binary files.

**Comment by filipovskid** [comment]
Hello @SemyonSinchenko, thank you for the issue! Would it be correct to rephrase the goal to the following points:

> - Provide a DDL file for managing the DB schema
> - Provide DML queries that populate the DB with test data
> - On server startup create DB objects and populate it with sample data as defined by the DDL and DML queries

Is it safe to assume that we want to move away from Hibernate-generated schema? (I am unsure if this is the case since the DB binary is already in the repo and I can't test at the moment)

**Comment by SemyonSinchenko** [comment]
> Would it be correct to rephrase the goal to the following points

Exactly!

**Comment by filipovskid** [comment]
Thank you! Sounds like a plan.

I am currently not holding this issue, so if someone is interested they can pick it up. If no one picks it up I will start working on it over the weekend - a comment will be added accordingly.

**Comment by SemyonSinchenko** [comment]
@filipovskid I would like to try to do it!

So, how I see it:
1. A bunch of SQL-files that directly creates tables with all the values of the current `db` file;
2. An extension of the `bin/bin/start-uc-server` script: I will add a branch so if the `db` file does not exist, all the SQL-files should be run one-by-one;

For running I would usu h2 RunScript. A dependency (h2 jar) I would take from the `target` folder of unitycatalog server. It is already there: https://github.com/unitycatalog/unitycatalog/blob/main/build.sbt#L161

**Comment by filipovskid** [comment]
Great! Feel free to ping me on the [slack channel](https://app.slack.com/client/T077J4Q91QR/C076YREKX8W) if you get stuck. @MrPowers please assign this to @SemyonSinchenko.

As for the implementation, I would say that it is even easier than you think. H2 supports this out of the box, and you can define the DDL and DML files to execute on a client connection. `INIT` command should do this for you, check [Execute SQL on Connection](https://www.h2database.com/html/features.html). With this approach we could easily remove this logic if we move to a different DBMS.

The documentation is your best friend.

**Comment by tdas** [comment]
@ravivj-db @vikrantpuppala these are very good ideas, please take note. 
My suggestion is as follows: 
- I know that there exists a script / code somewhere that we had used to generate this h2 database. let's first put that code out with possibly a test to ensure that starting from an empty database, if that code is run, it does generate the right database that satisfies the `tests/test_tutorial.py`
- then we can figure out which method of generating this database is better and improve things accordingly.

**Comment by ravivj-db** [comment]
Adding the existing java script to recreate the database via this PR : https://github.com/unitycatalog/unitycatalog/pull/156

**Comment by MrPowers** [comment]
Is this done yet?

**Comment by SemyonSinchenko** [comment]
The original issue is resolved because tests have been added to the tutorial to check the consistency of the sample DB.
