### ISSUE TITLE
Make `uc` command output adjust to terminal width.

### ISSUE THREAD

**Issue by creechy** [unitycatalog/unitycatalog#157]
**Is your feature request related to a problem? Please describe.**

The fixed-width, tabular output of the `uc` command sometimes is of limited use because it can trim critical field values such as table names and table Ids. For example, with the sample tables, when you list them, the table `marksheet_uniform` is trimmed down to `marksheet,,,`, making it challenging to use in subsequent commands, like to `get` the table.

The `uc` command also uses a fixed-width table size, regardless of the size of the terminal.

**Describe the solution you would like**

It would be more useful to force specific fields to _always_ show their full values.

It would also be more useful to use all of the terminal width were possible. 

**Additional context**

Example of the current output, note the `name` and `table_id` columns are trimmed.

<img width="1413" alt="image" src="https://github.com/unitycatalog/unitycatalog/assets/1179360/2b65e346-d894-4352-a60f-142293b5ee27">

**Comment by MrPowers** [comment]
It'd be nice if the columns were pretty printed here:

<img width="989" alt="uc_create_table" src="https://github.com/unitycatalog/unitycatalog/assets/2722395/e2e36256-0a34-44b9-9616-3da771ea70ab">

It'd also be nice if these columns were not padded with extra whitespace:

<img width="644" alt="uc_quickstart_table_contents" src="https://github.com/unitycatalog/unitycatalog/assets/2722395/296b15c3-1df4-48be-9e02-100aac7a4513">

Could be nice if we exposed these DataFrames as pandas/Polars/PyArrow Datasets to allow for output customization.
