### ISSUE TITLE
How to use external Databases in the server.properties to persist metadata

### ISSUE THREAD

**Issue by wahahawasabi** [unitycatalog/unitycatalog#16]
within `etc/conf/server.properties` file, we can define if we want to set it to dev or test or false to persist the table metadata. Is it possible to use an external database like postgres or my own instance of h2db instead?

**Comment by HuyNguyen7994** [comment]
https://github.com/unitycatalog/unitycatalog/blob/af5c34244b513a7a34001da3c9297e3892204f9b/server/src/main/java/io/unitycatalog/server/persist/HibernateUtil.java#L39C1-L43C14

it seems currently only hard-coded h2db is supported

**Comment by tdas** [comment]
Yes, right now its hardcoded to h2 but it would be awesome to define interfaces such that any database can be plugged in.

**Comment by vikrantpuppala** [comment]
Addressed in #211
