### ISSUE TITLE
docs: add X Table integration page

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#160]
Useful resources to make this page:

* [this blog post](https://www.linkedin.com/pulse/getting-started-x-table-unity-catalog-universal-datalakes-soumil-shah-l3rpe/?trackingId=LfVbu4PjS5awh%2FRkjfeViA%3D%3D)
* [this blog post](https://medium.com/@kywe665/unity-catalog-oss-with-hudi-delta-iceberg-and-emr-duckdb-710ab8f8a7dc)
* [this video](https://www.youtube.com/watch?v=1SKQRrenBj4&t=3s)

**Comment by dipankarmazumdar** [comment]
@MrPowers - would love to add to this!

**Comment by dipankarmazumdar** [comment]
@MrPowers: added a PR - https://github.com/unitycatalog/unitycatalog/pull/330. PTAL.

**Comment by MrPowers** [comment]
This was merged!
