### ISSUE TITLE
Setup docs to deploy to docs.unitycatalog.io

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#172]
Setup a GitHub Action that can be run manually to deploy the docs to docs.unitycatalog.io.

**Comment by nkarpov** [comment]
mkdocs has a built-in approach: https://www.mkdocs.org/user-guide/deploying-your-docs/ 

if it meets requirements, steps are: 

1. someone with write access run `gh-deploy mkdocs`, this creates a `gh-pages` branch
2. add CNAME record for `docs.unitycatalog.io` to point to `unitycatalog.github.io` (more [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain))

Did this on my own fork for reference:
https://github.com/nkarpov/unitycatalog/tree/gh-pages
https://unity.nickkarpov.com/

**Comment by dennyglee** [comment]
Currently, this has been manually created (vs. using GitHub Action) with subdomain forwarding due to some issues with the `CNAME` configuration.  Please review and if this looks good, we can work on updating this to a GitHub Action and potentially reconfigure the mkdocs CNAME configuration,

**Comment by MrPowers** [comment]
These are setup now: https://docs.unitycatalog.io/

Thanks @dennyglee!
