### ISSUE TITLE
Add server support for updating properties in catalog and schema 

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#175]
**Is your feature request related to a problem? Please describe.**

Currently, the update operations for catalog and schema do not support updating properties.

**Describe the solution you would like**

The `UpdateCatalog`/`UpdateSchema` objects can already take in properties. We would like to take these properties and overwrite any existing properties the entity has.
For example:
if we have a catalog: `catalog1` with properties `{prop1 -> value1, prop2 -> value2}`
and we call the update endpoint with new properties `{prop2 -> value4, prop3 -> value3}`
`catalog1` should have the properties `{prop2 -> value4, prop3 -> value3}`

**Additional context**

Rough idea on how to do this for catalog (schema would be similar)
- If properties is supplied in the UpdateCatalog object, [`updateCatalog`](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/CatalogRepository.java#L117) must remove existing properties and update those with the new properties supplied.
- This [function](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/PropertyRepository.java#L16) is used to interact with properties.
- Corresponding test cases must be added [here](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/test/java/io/unitycatalog/server/base/catalog/BaseCatalogCRUDTest.java#L59) to ensure behaviour is as expected.

Please feel free to reach out on [slack](https://go.unitycatalog.io/slack) if you need more details

**Comment by tlm365** [comment]
Seems like we need to solve this and #176 in the same PR, since both `cli` and `server`'s unit tests are based on `BaseCatalogCRUDTest`. If so, is it fine if we solve both in one PR @vikrantpuppala ?

**Comment by vikrantpuppala** [comment]
I'd prefer to keep the PRs small so that we can quickly review and merge, if combining both issues would still keep it small then I'm good. Else, for update, we can ignore the properties in CliOperations for now and not do any asserts and that can go in with #176
