### ISSUE TITLE
Add CLI support to provide properties for catalog and schema

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#176]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way to provide properties for catalog and schema via the CLI

**Describe the solution you would like**

We should be able to provide a json format of a map of properties in the CLI for create and update operations. Ex: `--properties '{"key1": "value1", "key2": "value2"}'`

**Additional context**

- This is already implemented for tables [here](https://github.com/unitycatalog/unitycatalog/blob/ed2ad4af6fbd663e45a0271c2a750d9e2acab9eb/examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java#L86). We should try to expand on the same and reuse the same code.
- We would also need to correspondingly update the optional and required params [here](https://github.com/unitycatalog/unitycatalog/blob/ed2ad4af6fbd663e45a0271c2a750d9e2acab9eb/examples/cli/src/main/java/io/unitycatalog/cli/utils/CliUtils.java#L76).
- Preferably add test cases that ensure feature completeness. For example [here](https://github.com/unitycatalog/unitycatalog/blob/ed2ad4af6fbd663e45a0271c2a750d9e2acab9eb/examples/cli/src/test/java/io/unitycatalog/cli/catalog/CliCatalogOperations.java#L28).
- This should also unblock us to fix [these](https://github.com/unitycatalog/unitycatalog/blob/ed2ad4af6fbd663e45a0271c2a750d9e2acab9eb/server/src/test/java/io/unitycatalog/server/base/catalog/BaseCatalogCRUDTest.java#L24) TODOs.

Please feel free to reach out on [slack](https://go.unitycatalog.io/slack) if you need additional details.

**Comment by mayank-gupta16** [comment]
Hi Vikrant, I would like to work on this issue. Can I pick this up?

**Comment by vikrantpuppala** [comment]
Yes, please!

**Comment by vikrantpuppala** [comment]
@vksx would you be able to pick this one up since you have more context with the CLI? 
You could use #220 to get started (most likely only need to address the comments)

**Comment by vksx** [comment]
Sure, I'll take this.

**Comment by VillePuuska** [comment]
This could be closed as done with #338 merged.
