### ISSUE TITLE
Improve list tables endpoint result 

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#177]
**Is your feature request related to a problem? Please describe.**

Currently, the result of the list tables API is returned in the descending order of updated time and the updated time is then used as the next page token. This is not very stable.

**Describe the solution you would like**

A better way to handle pagination and order would be to rely on the table name.

**Additional context**

- We should create an index on the table name as done [here](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/dao/TableInfoDAO.java#L19) in hibernate.
- We should then change [this query](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/TableRepository.java#L267) to use the table name.
- We should also update the [pagination token logic](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/TableRepository.java#L273) accordingly based on the query above.
- Add test cases that test the pagination logic and behaviour [here](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/test/java/io/unitycatalog/server/base/table/BaseTableCRUDTest.java#L69).
- This could also be extended to list catalogs/schemas/volumes/functions etc.

Please feel free to reach out on [slack](https://go.unitycatalog.io/slack) if you need additional pointers.

**Comment by munish7771** [comment]
@vikrantpuppala Looking to get familiar with UC. Can I pick this up?

**Comment by vikrantpuppala** [comment]
@munish7771 yes please! happy to have more contributors :)

**Comment by munish7771** [comment]
@vikrantpuppala 
_This could also be extended to list catalogs/schemas/volumes/functions etc._
is this change **required** for this issue?

**Comment by vikrantpuppala** [comment]
We could do those as a separate issues. Let's start with a PR specific to tables.
