### ISSUE TITLE
`databricks` unity catalog credentials fetching intended to be accessible externally?

### ISSUE THREAD

**Issue by ion-elgreco** [unitycatalog/unitycatalog#2]
Someone pointed me to the duckdb-uc implementation https://github.com/delta-io/delta-rs/discussions/2066#discussioncomment-9698087, https://github.com/duckdb/uc_catalog/blob/4a2ba143eb8686becf69f759caa731742c2d7c81/src/uc_api.cpp#L120, so I started trying out the `temporary table credentials` api last week.

However seems to be disallowed to do this from a non-databricks environment. Can someone shed some light on this?

```
{'error_code': 'UNAUTHENTICATED',
 'message': "Request to generate access credential for table '<redacted>' from outside of Databricks Unity Catalog enabled compute environment is denied for security. Please contact Databricks support for integrations with Unity Catalog.",
 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo',
   'reason': 'UNITY_CATALOG_EXTERNAL_GENERATE_TABLE_CREDENTIALS_DENIED',
   'domain': 'unity-catalog.databricks.com',
   'metadata': {'tableId': '<redacted>'}},
  {'@type': 'type.googleapis.com/google.rpc.RequestInfo',
   'request_id': '<redacted>',
   'serving_data': ''}]}
```

**Comment by jaychia** [comment]
Also encountering this error when reading from outside databricks. Is there some kind of special permissioning I need to set?

**Comment by jaychia** [comment]
<img width="1097" alt="image" src="https://github.com/unitycatalog/unitycatalog/assets/17691182/eb2d1d42-3466-4147-b42a-898fde16bed1">

Seems to also be happening even if I'm running from inside a databricks notebook (but not from inside a databricks Spark cluster)

**Comment by ramesh-db** [comment]
Thank you for trying things out! This seems to be related to Databricks Unity Catalog. Please file a Databricks support ticket to get this resolved. That said, if you try OSS Unity Catalog and run into issues, please don't hesitate to open another issue!
