### ISSUE TITLE
[Solution] [error] java.lang.NoClassDefFoundError: Could not initialize class sbt.internal.parser.SbtParser$

### ISSUE THREAD

**Issue by srikanthgr** [unitycatalog/unitycatalog#20]
**Issue Description**

I was facing the following error when using Java version java 22.0.1 2024-04-16:

`java.lang.NoClassDefFoundError: Could not initialize class sbt.internal.parser.SbtParser$`

**Resolution**

To resolve the build issue, I changed the sbt version to the latest version in the **unitycatalog/project/build.properties** file: 

`sbt.version=1.10.0`

Updating the sbt version to 1.10.0 resolved the build issue.

**Comment by VillePuuska** [comment]
Same issue with openjdk 21.0.3 2024-04-16 and the fix worked, thank you!

**Comment by rameshchandra** [comment]
Thank you for raising this issue. #12 fixes this issue. Please reopen if it doesn't.
