### ISSUE TITLE
Upgrade to more current version of Java

### ISSUE THREAD

**Issue by creechy** [unitycatalog/unitycatalog#209]
**Is your feature request related to a problem? Please describe.**

Currently the codebase requires Java 11 and forces the source and target language levels to 1.8. Both of these are a little old. Barring and restrictions due to dependencies, the code base should be upgraded to a newer Java release. The benefits include the ability to use newer java syntax and APIs. 

**Describe the solution you would like**

I would suggest upgrading to Java 17. It's not the most recent (Java 21) but has good overall support across open source frameworks and APIs.

**Comment by MrPowers** [comment]
This was merged, great work!
