### ISSUE TITLE
Add Support for Models

### ISSUE THREAD

**Issue by monamohan** [unitycatalog/unitycatalog#234]
**Is your feature request related to a problem? Please describe.**

This is an umbrella issue around UC OSS CRUD support for models

**Describe the solution you would like**

 [x] Implement the API definition for the UC models CRUD API [#270]
 [x] Implement UC backend CRUD handlers for Registered Models [#344]
 [x] Implement UC backend CRUD handlers for Model Versions [#371]
 [x] Build Model Version Credential handler [#384]
 [x] Test framework for UC model CRUD handlers

**Additional context**

Models functionality and documentation is ready to go and will ship with v0.2

**Comment by kriscon-db** [comment]
You can assign to me

**Comment by everettVT** [comment]
@kriscon-db any chance you are planning for integration with mlflow model registry and experiment tracking?

**Comment by kriscon-db** [comment]
> @kriscon-db any chance you are planning for integration with mlflow model registry and experiment tracking?

That is indeed the initial plan (at least with regards to model registry).  We will be introducing a UC OSS rest store into mlflow in order for the mlflow client to be able to talk directly to UC OSS to manage model registry functionality.  There are no immediate plans to add experiment tracking into UC OSS at this time.

**Comment by rickyma** [comment]
@kriscon-db What is the timeline for completing this current issue with multiple features.

**Comment by kriscon-db** [comment]
> Hey @kriscon-db, Could you please tell me what is the timeline for completing this current issue with multiple features.

I am actively working on this now and should start having PRs for folks to look at next week.  As for completion of this whole issue, you're probably looking at 2-3 weeks though.

**Comment by rickyma** [comment]
Thanks. Good to know this. I can't wait to use it.

Is there a way to speed this up? Is there something I might be able to help you with?

**Comment by kriscon-db** [comment]
> Thanks. Good to know this. I can't wait to use it.
> 
> Is there a way to speed this up? Is there something I might be able to help you with?

Sorry I forgot to respond to this.  We had some headaches getting reviewers which caused the initial delay.  I've landed the model PR and am working with the reviewer on the model version PR.  I'll have the credential handler PR shortly after that lands.

Concurrently, we are working on the MLflow commit now that will add UC OSS support such that you will be able to configure you registry URI to point to a UC OSS server and have that act as your model registry.

**Comment by everettVT** [comment]
This is exactly what I was hoping for @kriscon-db, thanks so much.

**Comment by kriscon-db** [comment]
Feature landed in v0.2
