### ISSUE TITLE
0.2.0-SNAPSHOT version in version.sbt (main branch)

### ISSUE THREAD

**Issue by jaceklaskowski** [unitycatalog/unitycatalog#235]
After [Unity Catalog 0.1](https://github.com/unitycatalog/unitycatalog/releases/tag/v0.1.0), [version.sbt](https://github.com/unitycatalog/unitycatalog/blob/main/version.sbt) should be `0.2.0-SNAPSHOT`, huh?!

/cc @tdas

**Comment by MrPowers** [comment]
I think we normally bump that file right before making the release.  But the release devs know more than me on this one.

**Comment by tdas** [comment]
No no @jaceklaskowski is right. We should bump it up to 0.2.0-snapshot. care to do the honours @jaceklaskowski :)
