### ISSUE TITLE
[docs]: server.md - logical inconsistency in `server.env` property description

### ISSUE THREAD

**Issue by dmoore247** [unitycatalog/unitycatalog#24]
This paragraph is not logically consistent. It first states the valid values are 'dev' or 'test' then goes on to say if set to 'false'.

> The server config file is at the location etc/conf/server.properties (relative to the project root).
> 
> server.env: The environment in which the server is running. **This can be set to dev or test**. When set to test the server will instantiate an empty in-memory h2 database for storing metadata. **If set to false, the** server will use the file etc/db/h2db.mv.db as the metadata store. Any changes made to the metadata will be persisted in this file.
>

**Comment by rameshchandra** [comment]
Thank you for finding this typo. Create PR #60 to fix it.
