### ISSUE TITLE
Add a section to the README for Language Bindings/Clients

### ISSUE THREAD

**Issue by slyons** [unitycatalog/unitycatalog#249]
**Is your feature request related to a problem? Please describe.**

I'm working on a [Rust binding](https://github.com/slyons/unitycatalog-rs) for the Unity Catalog API and I'd love to share it with others.

**Describe the solution you would like**

A section in the README for all of the future Client libraries/bindings for working with Unity Catalog

**Comment by MrPowers** [comment]
@slyons - thanks for the suggestion.

There is a [unitycatalog/unitycatalog-rs](https://github.com/unitycatalog/unitycatalog-rs) initiative that's ongoing.  Have you considered contributing to that repo?

**Comment by slyons** [comment]
I didn't even know it existed. All of the hype has been around the fact that it's been released in Java. I'll see about folding my changes into that repo instead.

**Comment by MrPowers** [comment]
Yea, we'd love to collaborate with you @slyons, thank you!
