### ISSUE TITLE
Allow configuration of server port for Unity Catalog

### ISSUE THREAD

**Issue by shubh1205** [unitycatalog/unitycatalog#250]
**Description:**

Currently, the Unity Catalog server runs only on port 8080 and also some internal process uses port 8081. At least from the docs I could not find any way to configure these ports. This limits flexibility when deploying the server in environments where port 8080 or 8081 might be occupied by another application.

**Enhancement Request:**

I would like to request an enhancement that allows configuration of the server port. This would provide greater control and flexibility during deployment, especially in scenarios where port 8080 is unavailable.

**Proposed Solution:**

There are two possible approaches to achieve this:

- Configuration File: Introduce a configuration file (e.g., application.properties or server.properties) where the server port can be specified. This file would be loaded during server startup, allowing users to customize the port value.

- Command-Line Argument: Alternatively, consider adding a command-line argument (e.g., -p or --port) that accepts the desired port number. This would provide a more dynamic way to configure the port at runtime.

**Benefits:**

- Increased flexibility during deployment, allowing users to avoid conflicts with other applications using port 8080.
- Improved maintainability by separating configuration from code.
- Enhanced user experience by providing more control over server startup behavior.

**Comment by filipovskid** [comment]
This is a great first issue—thank you for opening it! If anyone wants to volunteer, feel free to snatch this up! :bowtie:

**Comment by vksx** [comment]
@vikrantpuppala I can take this up.

**Comment by vikrantpuppala** [comment]
Thank you very much @vksx! Assigned the issue to you :)
