### ISSUE TITLE
Refactor table service configuration to match style of other services

### ISSUE THREAD

**Issue by creechy** [unitycatalog/unitycatalog#257]
**Is your feature request related to a problem? Please describe.**

Just a code style change. The table service is configured differently than other services with Armeria

```java
        .annotatedService(basePath + "schemas", schemaService, unityConverterFunction)
        .annotatedService(basePath + "volumes", volumeService, unityConverterFunction)
        .annotatedService(basePath, tableService, unityConverterFunction)
```

The service paths configured by concatenating to the base path, except for table service.

**Describe the solution you would like**

Refactor table service configuration and endpoints appropriately.

**Additional context**

**Comment by vikrantpuppala** [comment]
Fixed by #258
