### ISSUE TITLE
SLF4J Warnings showing up when starting the UC Server in CLI

### ISSUE THREAD

**Issue by vksx** [unitycatalog/unitycatalog#269]
**Describe the bug**

Getting the following SLF4J warnings when starting the UC Server:
- [No SLF4J providers were found](https://www.slf4j.org/codes.html#noProviders).
- [Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier](https://www.slf4j.org/codes.html#ignoredBindings).

**To Reproduce**

1. `build/sbt package`
2. `bin/start-uc-server`

**Expected behavior**

We should get rid of these warnings.

**System [please complete the following information]:**

-   OS: macOS Sonoma 14.5

**Additional context**

As mentioned [here](https://logging.apache.org/log4j/2.x/log4j-slf4j-impl.html#:~:text=log4j%2Dslf4j2%2Dimpl%20should%20be%20used%20with%20SLF4J%202.0.x%20releases%20or%20newer.) we can get rid of the warnings if we replace `log4j-slf4j-impl` with `log4j-slf4j2-impl` in [`build.sbt`](https://github.com/unitycatalog/unitycatalog/blob/main/build.sbt) [here](https://github.com/unitycatalog/unitycatalog/blob/79a2ad9a9ad842f4fb82dcca3e624928a666992c/build.sbt#L178) and [here](https://github.com/unitycatalog/unitycatalog/blob/79a2ad9a9ad842f4fb82dcca3e624928a666992c/build.sbt#L275). 

Please let me know if this makes sense. Thanks!

**Comment by jaceklaskowski** [comment]
Apache Spark and Delta Lake use slf4j for logging and am wondering why UC chose another lib? Perhaps UC could (should?) use the same logging lib?

**Comment by jaceklaskowski** [comment]
The following should work in `commonSettings`:

```
  libraryDependencies ++= Seq(
    "org.slf4j" % "slf4j-api" % "2.0.13",
    "org.slf4j" % "slf4j-log4j12" % "2.0.13" % Test,
    "org.apache.logging.log4j" % "log4j-slf4j2-impl" % "2.23.1",
    "org.apache.logging.log4j" % "log4j-api" % "2.23.1",
  ),
```

Let me know @vksx if you wanna work on it. I can support you if needed.

**Comment by vksx** [comment]
@jaceklaskowski Sure, I'll take this up. I will add the recommended changes to `commonSettings`.
