### ISSUE TITLE
Add python sdk

### ISSUE THREAD

**Issue by tdas** [unitycatalog/unitycatalog#286]
**Is your feature request related to a problem? Please describe.**

Just like we have the openapi generated java client sdk, there needs to be generated Python sdk for python integrations with UC.

**Describe the solution you would like**

It's important for auto-generated client SDKs to be coversioned with the server with the API spec and the server supporting the spec. Hence it's best if all the auto-generated clients ar in this repo so that all of them can released together. Otherwise it is going to be a major version hell if the server of version x is going to be compatible with java sdk version x (since java is already in this repo), python sdk version y, c++ sdk version z, etc. 

I think the best way to proceed is to add the python generation in the sbt project in the same way as that has been added for java. 
- location: clients/python 
- open API generation configuration: same as the current python sdk 0.1 released in pypi.

**Comment by MrPowers** [comment]
Thanks @tdas!  Linking the related discussion: https://github.com/unitycatalog/unitycatalog/discussions/213

**Comment by kevinzwang** [comment]
I can take this!

**Comment by MrPowers** [comment]
@kevinzwang - sweet, assigned this one to you! 😎

**Comment by noklam** [comment]
I found this today https://github.com/unitycatalog/unitycatalog-python, was it mean to be maintained as a separate project?

**Comment by kevinzwang** [comment]
> I found this today https://github.com/unitycatalog/unitycatalog-python, was it mean to be maintained as a separate project?

Pulling the code from that repo into here would be one possible method, but we would like to explore using open-source alternatives to Stainless first

**Comment by yusufhalabi** [comment]
@kevinzwang Hey Kevin, at Fern (buildwithfern.com) we offer open-sourced SDK generation and would love to demo an idiomatic python SDK for you. Interested in chatting?
