### ISSUE TITLE
Improve availability of the documentation

### ISSUE THREAD

**Issue by fpgmaas** [unitycatalog/unitycatalog#33]
**Is your feature request related to a problem? Please describe.**

Currently, the documentation seems to only be available as markdown files in the github repository. This is not very user friendly.

**Describe the solution you would like**

I think it would be a good idea to host the documentation as a static website.

**Additional context**

I opened a PR that proposes a solution with mkdocs https://github.com/unitycatalog/unitycatalog/pull/32

**Comment by MrPowers** [comment]
Thanks again for getting this one started @fpgmaas.

I am working on restructuring the docs a bit and hopefully we can go live with the first version of the docs on docs.unitycatalog.io soon!

**Comment by monamohan** [comment]
@MrPowers What are the next steps here?

**Comment by MrPowers** [comment]
@monamohan - we're working on some CNAME issues right now and need to build a GitHub Action to release the docs on command.  Hopefully we can get this done soon 😄

**Comment by MrPowers** [comment]
This is done!  https://docs.unitycatalog.io/
