### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by francisco-ltech** [unitycatalog/unitycatalog#339]
**Describe the bug**

Docker container fails to start after successful docker image build

**To Reproduce**

1. git clone https://github.com/unitycatalog/unitycatalog.git
2. docker/bin/build-uc-server-docker
3. docker/bin/start-uc-server-in-docker

**Expected behavior**

Docker container should start successfully

**System [please complete the following information]:**

-   OS: MacOS

**Additional context**

2024-08-12 09:47:02 + set -ex
2024-08-12 09:47:02 +++ readlink -f bin/start-uc-server
2024-08-12 09:47:02 ++ dirname /opt/unitycatalog/bin/start-uc-server
2024-08-12 09:47:02 + SCRIPT_DIR=/opt/unitycatalog/bin
2024-08-12 09:47:02 ++ dirname /opt/unitycatalog/bin
2024-08-12 09:47:02 + ROOT_DIR=/opt/unitycatalog
2024-08-12 09:47:02 ++ find /opt/unitycatalog/server/target -name 'unitycatalog-server*.jar'
2024-08-12 09:47:02 ++ head -n 1
2024-08-12 09:47:02 + SERVER_JAR=/opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
2024-08-12 09:47:02 + '[' -z /opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar ']'
2024-08-12 09:47:02 + relative_path_to_jar=server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
2024-08-12 09:47:02 + SERVER_JAVA_COMMAND='java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar'
2024-08-12 09:47:02 + cd /opt/unitycatalog
2024-08-12 09:47:02 + exec java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
2024-08-12 09:47:02 Error: Unable to initialize main class io.unitycatalog.server.UnityCatalogServer
2024-08-12 09:47:02 Caused by: java.lang.NoClassDefFoundError: com/linecorp/armeria/server/HttpService

**Comment by jaceklaskowski** [comment]
Took me quite some time to reproduce on my end and think I've got it yet a different error.

```console
❯ docker ps -a --no-trunc
CONTAINER ID                                                       IMAGE                         COMMAND                               CREATED         STATUS                     PORTS     NAMES
2bca8223e6f3b986cc1e528b1fea4a131e40d5fed3cdb1ccd785ccfb157c67d0   unitycatalog:0.2.0-SNAPSHOT   "/bin/bash -ex bin/start-uc-server"   2 minutes ago   Exited (1) 2 minutes ago             unitycatalog
```

```console
❯ docker container logs 2bca8223e6f3b986cc1e528b1fea4a131e40d5fed3cdb1ccd785ccfb157c67d0
+ set -ex
+++ readlink -f bin/start-uc-server
++ dirname /opt/unitycatalog/bin/start-uc-server
+ SCRIPT_DIR=/opt/unitycatalog/bin
++ dirname /opt/unitycatalog/bin
+ ROOT_DIR=/opt/unitycatalog
++ find /opt/unitycatalog/server/target -name 'unitycatalog-server*.jar'
++ head -n 1
+ SERVER_JAR=/opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar
+ '[' -z /opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar ']'
+ relative_path_to_jar=server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar
+ SERVER_JAVA_COMMAND='java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar'
+ cd /opt/unitycatalog
+ exec java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar
no main manifest attribute, in server/target/unitycatalog-server-0.2.0-SNAPSHOT-sources.jar
```

Both errors should be fixed. Let me start with mine first 😉

**Comment by jaceklaskowski** [comment]
At long last I managed to reproduce your issue 🥳 

```console
docker run --rm --entrypoint /bin/sh -it unitycatalog:0.2.0-SNAPSHOT
```

```console
/opt/unitycatalog $ /opt/unitycatalog/bin/start-uc-server
+ readlink -f /opt/unitycatalog/bin/start-uc-server
+ dirname /opt/unitycatalog/bin/start-uc-server
+ SCRIPT_DIR=/opt/unitycatalog/bin
+ dirname /opt/unitycatalog/bin
+ ROOT_DIR=/opt/unitycatalog
+ SERVER_JAR=/opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
+ '[' -z /opt/unitycatalog/server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar ]
+ relative_path_to_jar=server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
+ SERVER_JAVA_COMMAND='java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar'
+ cd /opt/unitycatalog
+ exec java -jar server/target/unitycatalog-server-0.2.0-SNAPSHOT.jar
Error: Unable to initialize main class io.unitycatalog.server.UnityCatalogServer
Caused by: java.lang.NoClassDefFoundError: com/linecorp/armeria/server/HttpService
```

**Comment by dennyglee** [comment]
@jaceklaskowski and @francisco-ltech, by any chance, do you not have Java installed or in the path?  Don't get me wrong, the docker should be self-contained, but I'm wondering if that's what we missed based on the error.

**Comment by francisco-ltech** [comment]
@dennyglee I do.

openjdk version "22.0.2" 2024-07-16

I just saw another bug issue where someone reported that the project does not compile in 21 and 22 so not sure if that issue has to do with this one. Not an expert in JVM but I would also expect that the docker should be self-contained.

**Comment by dennyglee** [comment]
@francisco-ltech Ah got it - I think we've defaulted to Java 17 so this may be in play on why you're getting the error.  Saying this, you're right, this is a bug, we need to have the docker pre-install the correct Java so it isn't impacted by whatever version you're running.

**Comment by jaceklaskowski** [comment]
@dennyglee After [this](https://github.com/unitycatalog/unitycatalog/commit/119f4707d033add34c0894916f544785e110fe94) and now [this](https://github.com/unitycatalog/unitycatalog/commit/009ac77e7cd7926acb061ed1b8b5c3e5177c1bf7) commits, docker module uses wrong incomplete jar file 🤷

**Comment by jaceklaskowski** [comment]
It's been on my todo list for over a week now and just before I go for vacation here comes a [PR](https://github.com/unitycatalog/unitycatalog/pull/367)! 🥳 

Please review @dennyglee 🙏

**Comment by dennyglee** [comment]
Thanks @jaceklaskowski - looking at this now - really appreciate this!
