### ISSUE TITLE
UC Swagger

### ISSUE THREAD

**Issue by dennyglee** [unitycatalog/unitycatalog#343]
**Is your feature request related to a problem? Please describe.**
We need to create UC swagger docs

**Describe the solution you would like**
Currently, the UC APIs can be found at https://go.unitycatalog.io/apidocs; we should update them to be swagger to simplify API development. 

**Additional context**

**Comment by sudharshanraja-db** [comment]
Hi @dennyglee I am interested in exploring and  taking up this task

**Comment by dennyglee** [comment]
Oh sure @sudharshanraja-db - that would be awesome!  With the work for the various clients, it would be great if you’re up for tackling this, eh?!

**Comment by sudharshanraja-db** [comment]
Hi @dennyglee   Based on my analysis , This is  the approach i am thinking of  but thought would get feedback 

Armeria already provides doc service ,  to expose it to swagger 
1. Armeria exposes open api spec use this to render on swagger UI
2. Clone the swagger UI and modify the index.html to point to open api spec
3. Publish the docs to github pages

Additionally for the above we might need to set some cors configuration 
Let me know your thoughts

**Comment by dennyglee** [comment]
> Hi @dennyglee Based on my analysis , This is the approach i am thinking of but thought would get feedback
> 
> Armeria already provides doc service , to expose it to swagger
> 
> 1. Armeria exposes open api spec use this to render on swagger UI
> 2. Clone the swagger UI and modify the index.html to point to open api spec
> 3. Publish the docs to github pages
> 
> Additionally for the above we might need to set some cors configuration Let me know your thoughts

Thanks @sudharshanraja-db - yes, I think that makes sense.  Glad to hear any others that may have thoughts about this approach but I think this is a great fast way to kick start the process, eh?!  Appreciate you diving into this!
