### ISSUE TITLE
Wrong storage location of table marksheet_uniform in default H2 db

### ISSUE THREAD

**Issue by ideal** [unitycatalog/unitycatalog#354]
**Describe the bug**

When running with dev mode and default H2 db file, the storage location of table `unity.default.marksheet_uniform` is file:///tmp/marksheet_uniform, which is not correct.

**To Reproduce**

1. Build and running unitycatalog with default H2 db: `bin/start-uc-server`.
2. Run `bin/uc table get --full_name unity.default.marksheet_uniform` to get its storage location: file:///tmp/marksheet_uniform

**Expected behavior**

The storage location should be a absolute path to `etc/data/external/unity/default/tables/marksheet/`.

**System [please complete the following information]:**

-   OS: Arch Linux

**Additional context**

None.

**Comment by SemyonSinchenko** [comment]
Can I try to fix it? I already had an experience with DB population script.

**Comment by ideal** [comment]
I found the document at: https://github.com/unitycatalog/unitycatalog/blob/main/docs/usage/tables/uniform.md

We need to copy files:

```
A pre-populated Delta Uniform table can be prepared by running cp -r etc/data/external/unity/default/tables/marksheet_uniform /tmp/marksheet_uniform.
```
