### ISSUE TITLE
Read & Write in UC tables with polars

### ISSUE THREAD

**Issue by oliverangelil** [unitycatalog/unitycatalog#401]
**Is your feature request related to a problem? Please describe.**

99.9% of the tables we use at the company I work for, don't require spark since they are not terabytes in size.  

**Describe the solution you would like**

[Polars ](https://github.com/pola-rs/polars) has impressive performance benchmarks, and is designed to work with dataframes. 
Would be great to be able to read/write UC delta tables using the UC pathname (not the table UID)

**Comment by VillePuuska** [comment]
Seconded. Would love to be able to get tables from UC directly to Polars dataframes and write dataframes directly to UC tables. I've actually built a [toy project](https://github.com/VillePuuska/Local-Lakehouse) to do exactly this when everything is local, i.e. locally running UC with no auth and tables stored locally.

I think once the Python SDK gets added (see #286 and #309) work on building this capability can start, whether it's included in UC, in Polars, or built as a completely separate package.

**Comment by francisco-ltech** [comment]
@oliverangelil By UC pathname do you mean the namespace? e.g.: catalog.schema.table? I think this is coming soon if I'm not mistaken.

Not sure if it helps, but in the meantime, you can still create your table metadata in UC via bin/uc table --full_name unity.default.data --storage_location "path/to/table" ...

Then, have polars to write the data to the location specified in the previous command.

**Comment by oliverangelil** [comment]
@francisco-ltech yes I mean the namespace (catalog.schema.table). Just like one can read a table with spark using `spark.table(catalog.schema.table)`
