### ISSUE TITLE
Add PATCH support for the /scim2/Users/<user-id> endpoint

### ISSUE THREAD

**Issue by creechy** [unitycatalog/unitycatalog#423]
**Describe the bug**

Configuring Okta SCIM2 with UC OSS doesn't delete/deactivate users when they are removed from the identity provider's sync.

**To Reproduce**

1. Configure Okta SCIM2 to point to a UC OSS server, easiest way is to use Okta's SCIM 2.0 Test App (OAuth Bearer Token) application.
2. Add a user to the Okta integration/assignment.
3. use `uc user list` to verify the user has been created.
4. Remove the user from the Okta integration/assignment. This should deactivate the user.
5. use `uc user list` and see that the user status is still ENABLED>

**Expected behavior**

When removing a user with Okta/SCIM, the user should be set to DISABLED in the UC OSS user database.

**System [please complete the following information]:**

**Additional context**

The SCIM2 protocol defines a couple of ways to update users, with PUT and PATCH commands. Currently the UC OSS `/scim2/Users/<user-id>` endpoint only supports PUT but Okta uses the PATCH command to deactivate the user.

**Comment by sudharshanraja-db** [comment]
Hi @creechy  I would like to explore and take this bug

**Comment by creechy** [comment]
> Hi @creechy I would like to explore and take this bug

@sudharshanraja-db go for it. Let me know if you have any questions. I _might_ be able to dig up some reference code from some separate work if you need.
