### ISSUE TITLE
 Tutorial Tests are failing because  uc_catalog extension is not available in duckdb nighly-extension build any more. 

### ISSUE THREAD

**Issue by yaoderek** [unitycatalog/unitycatalog#455]
uc_catalog extension is unavailable in duckdb nighly-extension build any more. This failed new PR builds, e.g.,  
https://github.com/unitycatalog/unitycatalog/actions/runs/10780247495/job/29895566657?pr=450

```
HTTPException:` HTTP Error: Failed to download extension "uc_catalog" at URL "http://nightly-extensions.duckdb.org/17d598fc44/osx_arm64/uc_catalog.duckdb_extension.gz" (HTTP 403)
```

Similar issue also reported in duckdb github repo.
https://github.com/duckdb/duckdb/discussions/13298

**Comment by vksx** [comment]
It is not failing now.
