### ISSUE TITLE
[DOCS] Update CLI page formatting closer to models

### ISSUE THREAD

**Issue by dennyglee** [unitycatalog/unitycatalog#545]
**Is your feature request related to a problem? Please describe.**

The [CLI page ](https://docs.unitycatalog.io/usage/cli/) should be closer to the [Models page](https://docs.unitycatalog.io/usage/models/) making use of:
* More admonitions, i.e. notes / warnings / tips
<img width="789" alt="Screenshot 2024-10-01 at 21 04 09" src="https://github.com/user-attachments/assets/c607fe59-f46f-4a0b-b388-50bc49f28ca1">

* More graphics/screen GIFs showing how the CLI works scubas this [MLflow animated GIF](https://docs.unitycatalog.io/assets/images/mlflow-unitycatalog-model-view-2.0.gif)

* More annotations

<img width="788" alt="Screenshot 2024-10-01 at 21 03 51" src="https://github.com/user-attachments/assets/4faeb7c8-dc52-467e-88d0-c94ef1fa2359">

**Describe the solution you would like**

As noted in the problem area, please provide more extensive documentation for the CLI. 

**Additional context**

**Comment by avriiil** [comment]
take
