### ISSUE TITLE
[DOCS] Breakout code blocks in Spark page

### ISSUE THREAD

**Issue by dennyglee** [unitycatalog/unitycatalog#548]
**Is your feature request related to a problem? Please describe.**

Let's clean up some of code blocks on the [Apache Spark](https://docs.unitycatalog.io/integrations/unity-catalog-spark/) docs.

* The *Merge mytable with srctable* should be broken out into separate commands with title.

* The output should be in `console` mode while the code should be in `sql` or `python` depending on the language used.  

* We should have `Spark SQL` and `PySpark` commands (currently its only showing Spark SQL) for the *Running CRUD Operations on a Unity Catalog table* section.

 

**Describe the solution you would like**

**Additional context**

**Comment by vksx** [comment]
take
