### ISSUE TITLE
[DOCS] Add mkdocs explanation to docs README.md

### ISSUE THREAD

**Issue by dennyglee** [unitycatalog/unitycatalog#550]
**Is your feature request related to a problem? Please describe.**

For developers that want to test out documentation:
* Use `mkdocs serve` to serve the docs locally 
* Test out using your own `pages repo`, you can run `mkdocs gh-deploy` against your GitHub repo - the docs will be delayed to `bobbiedraper.github.io/unitycatalog`

**Describe the solution you would like**

**Additional context**

**Comment by dennyglee** [comment]
done! @Brijeshthummar02

**Comment by Brijeshthummar02** [comment]
@dennyglee can you show me the path where to add file.

**Comment by dennyglee** [comment]
> @dennyglee can you show me the path where to add file.

Oh, could you add a README.md to the docs folder.  Let's not include it in the nav but it allows folks in the GitHub to understand how to run/build the docs locally and deploy onto GitHub pages locally.  Thanks!
