### ISSUE TITLE
Google Auth not working: token file not being created after restart

### ISSUE THREAD

**Issue by avriiil** [unitycatalog/unitycatalog#559]
**Describe the bug**

I am following the instructions as per https://docs.unitycatalog.io/server/auth/.
When I try to test authentication using `bin/uc --auth_token $(cat etc/conf/token.txt) user list` the following error is returned:

```
cat: etc/conf/token.txt: No such file or directory
```

It seems the token file is not being created. I also don't see the other internal signing keys and authentication files in `etc/conf`.

**To Reproduce**

1. Configure `etc/conf/server.properties` as instructed
2. Restart `bin/start-uc-server`
3. Test authentication with `bin/uc --auth_token $(cat etc/conf/token.txt) user list`

Confirming that I'm on the latest version of `main`. 

**Expected behavior**

authentication via Google Auth

**System [please complete the following information]:**

-   OS: MacOS 14.3.1

**Comment by dennyglee** [comment]
Sorry about this issue @avriiil  - I'm having a hard time reproducing this issue.  Just wanted to confirm that you had cleared out the previous `target` and downloaded the latest master or 0.2 release?
