### ISSUE TITLE
Add docs/readme.md

### ISSUE THREAD

**Issue by dennyglee** [unitycatalog/unitycatalog#628]
**Is your feature request related to a problem? Please describe.**

The way the `docs` is currently structured in the `unitycatalog` repo, it makes it look like these are the official docs.  Whereas the actual docs are located at https://docs.unitycatalog.io.   So instead of folks reading the docs from our docs page, they are reading the `mkdocs` source.

**Describe the solution you would like**

Suggest the following solution:
* Add a `readme.md` in the `docs` folder that is NOT included in the `mkdocs.yml` hierarchy
* Ensure `mkdocs.yml` skips the readme.md file
* Explain the process who to run/test/deploy the docs including references to GitHub pages.

**Additional context**

**Comment by HorizonNet** [comment]
take

**Comment by HorizonNet** [comment]
@dennyglee I think this one is similar to #550 and with some tweaks (updating `mkdocs.yml` and update the phrasing in `README.md`) it can be included into #631, which would also solve the `Docs Generation Test` failure in this one. What do you think? Or should I prepare the tweaks here and then we update the other PR and get it in?

**Comment by dennyglee** [comment]
@HorizonNet if you can prep the tweaks here and then we update the other PR to get it in that would be appreciated!  Thanks!

**Comment by HorizonNet** [comment]
@dennyglee PR is created. I kept it simple and leave most of the content of the README to #550.
