### ISSUE TITLE
Empty external table issue with spark-sql

### ISSUE THREAD

**Issue by ximmit** [unitycatalog/unitycatalog#630]
I am facing a problem with creating an external table in s3 (spark-sql). 
After creating it, I see an empty table with no column name. At the same time cli is working fine.

**Steps to reproduce the behavior:**

1. spark-sql --name "s3-uc-test" \
  --master "local[*]" \
  --packages "org.apache.hadoop:hadoop-aws:3.3.4,io.delta:delta-spark_2.12:3.2.1,io.unitycatalog:unitycatalog-spark_2.12:0.2.0" \
  --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
  --conf "spark.sql.catalog.spark_catalog=io.unitycatalog.spark.UCSingleCatalog" \
  --conf "spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem" \
  --conf "spark.sql.catalog.unity=io.unitycatalog.spark.UCSingleCatalog" \
  --conf "spark.sql.catalog.unity.uri=http://localhost:8080" \
  --conf "spark.sql.catalog.unity.token=TOKEN" \
  --conf "spark.sql.defaultCatalog=unity" \
 --conf "spark.hadoop.fs.s3a.access.key=ACCESS_KEY" \
 --conf "spark.hadoop.fs.s3a.secret.key=SECRET_KEY"

2. CREATE TABLE default.test_table (country STRING) USING delta LOCATION 's3a://amazingflags/raw/test_table';

3. SELECT * FROM default.test_table ;
24/10/15 04:45:05 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[DELTA_TABLE_NOT_FOUND] Delta table `default`.`test_table` doesn't exist

4. Check the empty table in Unity Catalog UI 

**Expected behavior**

An external table has been created. The Select query works and the table is displayed correctly in Unity Catalog

**System**

MacOs Sequoia 15.0.1 Apple M1 Pro

**Comment by jaceklaskowski** [comment]
This is because `s3a://` prefix is not recognized as a S3 bucket URL. You should use `s3://` instead and you should also set up `etc/conf/server.properties` properly as described in https://docs.unitycatalog.io/server/configuration/#configuration.

**Comment by ximmit** [comment]
This works well with the s3:// prefix and the defined storage configs in the properties.
