### ISSUE TITLE
Failure to build unity catalog server on Macbook

### ISSUE THREAD

**Issue by abrassel** [unitycatalog/unitycatalog#66]
**Describe the bug**

The Armeria dependency does not include the netty classfiles necessary to successfully compile and run unity catalog. 
This can be hacked around by specifying the transitive dependency (using "netty-all"). It is not yet clear why we must specify the upstream dependency manually.

**To Reproduce**

1. `build/sbt package`
2. `bin/start-uc-server`

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/ChannelPipeline
```

**Expected behavior**

I expected the script to successfully start the UC server.

**System [please complete the following information]:**

-   OS: Macos Sonoma (14.4.1 (23E224)), Apple M1 Max, Macbook Pro

**Comment by rameshchandra** [comment]
@abrassel Thanks for finding the issue. 

I couldn't repro the issue on a new checkout of the repo on a Macbook Pro with MacOS Sonoma after deleting my .ivy2 and .sbt folders. Would love to see a reliable repro.

**Comment by abrassel** [comment]
I'll let you know tomorrow!

**Comment by rameshchandra** [comment]
@abrassel closing this issue since PR #67 is merged. Please reopen if you still see this issue.
