### ISSUE TITLE
Timelines to make unitycatalog to feature complete for production usecases

### ISSUE THREAD

**Issue by krisnaru** [unitycatalog/unitycatalog#74]
**Is your feature request related to a problem? Please describe.**
As of now current version do not support production scale as it uses in memory database(H2) for [persistence](https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/persist/HibernateUtil.java#L40). 

Another feature is front end component for unity catalog(similar to databricks version)

**Describe the solution you would like**

Please fill the gaps between opensource and databricks version.

**Comment by dennyglee** [comment]
Thanks @krisnaru - could you please create a separate item for the front-end UI so we can track this separately as there are currently two initiatives that we can track with it. 

As for the database, yes - H2 is a great lightweight Java database so it’s a solid way to start.  We will start reviewing database options in the near future so will keep this issue open to continue to track its progress.

**Comment by MrPowers** [comment]
Feel free to track the project milestones for details on features and expected completion dates!
