### ISSUE TITLE
Trino Integration not able to access UC data

### ISSUE THREAD

**Issue by avriiil** [unitycatalog/unitycatalog#740]
**Describe the bug**

I'm testing the UC x Trino integration and running into some trouble. Both are running locally, Trino inside the latest trino Docker image.

I'm following the steps outline in [the docs](https://github.com/unitycatalog/unitycatalog/blob/main/docs/integrations/unity-catalog-trino.md):
1. start local UC server
2. set `iceberg.properties` in Trino Docker container as follows:

```
connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://127.0.0.1:8080/api/2.1/unity-catalog/iceberg
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.token=not_used
```

3. Launch Trino container and run SQL query from Trino CLI:

`SELECT * FROM iceberg."unity.default".marksheet_uniform;`

This fails with `Error 404 Not Found: HTTP 404 Not Found`, I presume because the local 8080 port can't be accessed from within the Docker container.

4. As suggested [here](https://github.com/trinodb/trino/issues/22609) I tried to forward the UC server to a remote port with serveo using `ssh -R 80:localhost:8080 serveo.net`
5. update the `iceberg.properties` accordingly:

`iceberg.rest-catalog.uri=http://<<servio-public-URL>>/api/2.1/unity-catalog/iceberg`

6. Run any SQL query (other than `SHOW CATALOGS;`) e.g. `SHOW SCHEMAS FROM iceberg;` throws this error:

`Malformed request: Must supply a proper catalog in warehouse property.`

**Expected behavior**

Access schema and table data.

**System [please complete the following information]:**

-   OS: e.g. MacOS 14.1.3
- Docker image: trinodb/trino:latest

[EDIT: accessing the Serveo URL in my browser shows me the `Hello, Unity Catalog!` message]

**Comment by tdas** [comment]
We are changing the configuration a little bit by requiring the warehouse property to specify which UC catalog to connect to. Here is the change we made - https://github.com/unitycatalog/unitycatalog/pull/324
This should be released as part of upcoming 0.2.1.

**Comment by avriiil** [comment]
Thanks for this @tdas, I've got it working now. I will update the Trino docs accordingly.

**Comment by avriiil** [comment]
closing this one, docs changes tracked in #744

**Comment by avriiil** [comment]
I celebrated too early -- I can now access schemas and list tables, but I cannot access data within tables. 

`SHOW TABLES FROM iceberg.default;` works
`SELECT * FROM iceberg.default.marksheet_uniform LIMIT 5;` throws:

`Failed to load table: marksheet_uniform in default namespace`

**Comment by tdas** [comment]
What is your full configuration in Trino.
also @alexreid-db can you help here since you implemented the warehouse change?

**Comment by avriiil** [comment]
Here's my full config:

```connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://abc.serveo.net/api/2.1/unity-catalog/iceberg
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.token=not_used
iceberg.rest-catalog.warehouse=unity
```

**Comment by avriiil** [comment]
It may be because Trino can’t access your localhost 30202 from inside the
Docker container. You need to forward it to a public URL, for example using
serveo or ngrok.

I’m working on more completed documentation, should be up in the next few
days.

**Comment by avriiil** [comment]
@alexreid-db - I'm wondering if you might have any suggestions here on how to resolve getting full access to the tables?

**Comment by creechy** [comment]
@avriiil I think the problem may be that Trino cannot access local files. I do get the same error as you, when looking at the failed jobs in the Trino UI, I see messages like 

```
Caused by: java.lang.IllegalArgumentException: No factory for location: file:/tmp/marksheet_uniform/metadata/snap-1249442174133317666-1-3d76bd5d-21ad-4512-9c62-35ddd82eceed.avro
```

Not sure if there is a way to get Trino to recognize/process local files.

**Comment by avriiil** [comment]
thanks for taking a look @creechy. is there anyone on the trino side we can ping about this @dennyglee @alexreid-db ?

**Comment by hoaihuongbk** [comment]
Got the same error like @student2o , have tried various kind of endpoint config but no luck. Networking should not issue since I tried to curl inside the trino docker image

```
$ curl http://uc-server:8080/api/2.1/unity-catalog/catalogs/unity
{"name":"unity","comment":"Main catalog","properties":{},"owner":null,"created_at":1721241605334,"created_by":null,"updated_at":null,"updated_by":null,"id":"f029b870-9468-4f10-badc-630b41e5690d"}
```

The list schemas API should work as well

```
$ curl http://uc-server:8080/api/2.1/unity-catalog/schemas?catalog_name=unity
{"schemas":[{"name":"default","catalog_name":"unity","comment":"Default schema","properties":{},"full_name":"unity.default","owner":null,"created_at":1721241605571,"created_by":null,"updated_at":null,"updated_by":null,"schema_id":"b08dfd57-a939-46cf-b102-9b906b884fae"},{"name":"demo_delta","catalog_name":"unity","comment":null,"properties":{"owner":"spark"},"full_name":"unity.demo_delta","owner":null,"created_at":1738224470848,"created_by":null,"updated_at":1738224470848,"updated_by":null,"schema_id":"d45ce147-4349-4c6a-92be-4478fa853406"},{"name":"demo_iceberg","catalog_name":"unity","comment":null,"properties":{"owner":"spark"},"full_name":"unity.demo_iceberg","owner":null,"created_at":1738226258350,"created_by":null,"updated_at":1738226258350,"updated_by":null,"schema_id":"88c808d5-b8da-4a0f-b4ca-d33c16e10874"},{"name":"demo_parquet","catalog_name":"unity","comment":null,"properties":{"owner":"spark"},"fu[
```
