### ISSUE TITLE
Introduce AssertJ for testing

### ISSUE THREAD

**Issue by nastra** [unitycatalog/unitycatalog#77]
It would be great to use [AssertJ](https://assertj.github.io/doc/)-style assertions for testing as those are more fluent and provide greater flexibility when asserting and testing code

**Comment by Cupprum** [comment]
Hi :) can you provide more description about why AssertJ should be preferred way of testing?

I would personally be interested in the following questions:
What are the other options?
Why is this one better?
What do other similar projects written in java use, and why should this one differ from the majority.

**Comment by nastra** [comment]
@Cupprum sure, I'll add some details below about AssertJ.

> What are the other options?

 Typically it would be JUnit4 or JUnit5 assertions, but I'll explain further below why AssertJ is a better choice here

> Why is this one better?

AssertJ gives you greater flexibility in testing and provides a fluent way of asserting things. 
Performing assertions on [Streams](https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/StreamAssertionsExamples.java#L51) / [Collections](https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/ListSpecificAssertionsExamples.java) / [Iterables](https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/IterableAssertionsExamples.java#L72) is a bit of a pain with plain JUnit assertions and the code rather ends up being much longer than needed, whereas the linked examples show that this can be achieved in a more concise and readable way.
Additionally, testing for a specific exception when code is being executed has been quite non-intuitive in JUnit.
With AssertJ exception testing is quite easy and can be done in a fluent way as can be seen in a few examples [here](https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/ExceptionAssertionsExamples.java#L38
).

>  What do other similar projects written in java use, and why should this one differ from the majority.

I've introduced AssertJ a few years ago to the Apache Iceberg project and we've never looked back at JUnit assertions. Additionally, AssertJ is being used in projects like Flink or Trino (just to name a few) and [this](https://github.com/search?q=org%3Aapache%20assertj&type=code) shows a wider variety of Apache projects where AssertJ is being used

**Comment by tdas** [comment]
@nastra thank you for that context. I agree that lets start using AssertJ if that is the new standard.
