### ISSUE TITLE
Repository is missing a `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by fpgmaas** [unitycatalog/unitycatalog#9]
There is some room for improvement for the repository to adhere to OSS community standards. For example, it is currently lacking issue templates, PR templates, but most importantly it is lacking a `CONTRIBUTING.md`. See also [here](https://github.com/unitycatalog/unitycatalog/community).

I made a start with a [PR for PR templates](https://github.com/unitycatalog/unitycatalog/pull/7) and a [PR for issue templates](https://github.com/unitycatalog/unitycatalog/pull/8).

In the proces of making Unity Catalog Open Source I believe it is important to also have a `CONTRIBUTING.md` so community members know how to contribute. 

<img width="904" alt="image" src="https://github.com/unitycatalog/unitycatalog/assets/12008199/c56b5b03-1543-4f3e-bf85-4ff870fe4741">

**Comment by tdas** [comment]
Thanks for catching! Will add.

**Comment by vinijaiswal** [comment]
@tdas I created a contributing guide and raised a PR https://github.com/unitycatalog/unitycatalog/pull/86
Can you please review to see it aligns with the project contribution guidelines. Thank you 🙏🏼

**Comment by rameshchandra** [comment]
PR #86 added a CONTRIBUTING.md
