### ISSUE TITLE
Remove redundant column properties from entity objects

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#92]
**Is your feature request related to a problem? Please describe.**

Currently, there are a few redundant column properties in the hibernate entity objects which can lead to confusion. Example: length of String is defined as 255 [here](https://github.com/unitycatalog/unitycatalog/blob/02ec950bf341390d6ca2c4b334257e36f02133cf/server/src/main/java/io/unitycatalog/server/persist/dao/ColumnInfoDAO.java#L45) but that is the default value hence, this is redundant.

**Describe the solution you would like**

Remove unnecessary redundant/default configs to avoid confusion and clean up the entities. Ensure all test cases are running post the removal.

**Additional context**

**Comment by filipovskid** [comment]
@vikrantpuppala I could pick this up
