### ISSUE TITLE
PropertyNamingStrategy.KebabCaseStrategy is deprecated and should not be used

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#93]
**Describe the bug**

A warning is thrown when running tests/bringing up the server informing that `PropertyNamingStrategy.KebabCaseStrategy` is deprecated and could cause deadlocks
```
[warn] /home/runner/work/unitycatalog/unitycatalog/server/src/main/java/io/unitycatalog/server/utils/RESTObjectMapper.java:45:1: com.fasterxml.jackson.databind.PropertyNamingStrategy.KebabCaseStrategy in com.fasterxml.jackson.databind.PropertyNamingStrategy has been deprecated
[warn] PropertyNamingStrategy.KebabCaseStrategy
Jun 25, 2024 9:25:56 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
WARNING: PropertyNamingStrategy.KebabCaseStrategy is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies.KebabCaseStrategy instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
```

**To Reproduce**

Run `build/sbt test`

**Expected behavior**

Deprecated classes should not be used. In this case, it could be replaced with `PropertyNamingStrategies.KebabCaseStrategy` and tested.

**System [please complete the following information]:**

-   OS: MacOS Sonoma 14.4.1

**Additional context**

[Code pointer](https://github.com/unitycatalog/unitycatalog/blob/02ec950bf341390d6ca2c4b334257e36f02133cf/server/src/main/java/io/unitycatalog/server/utils/RESTObjectMapper.java#L28) where this is used.

**Comment by VishnuT-Procore** [comment]
@vikrantpuppala / @tdas - I would like to pick this ticket

**Comment by vikrantpuppala** [comment]
I saw PR #94 out today that addresses this. However, there are other good first issues that you could help us out with! #92 and #91 for example.
