### ISSUE TITLE
Support running UC via a binary release

### ISSUE THREAD

**Issue by vikrantpuppala** [unitycatalog/unitycatalog#95]
**Is your feature request related to a problem? Please describe.**

Currently, the way to run the UC server and CLI is using the source code which internally uses sbt. To enable broader usage, we need a binary release and a way to run the server and CLI using the binary release.

**Describe the solution you would like**

A way to create binary releases and support to run UC using the binary.

**Additional context**

**Comment by gdubya** [comment]
A graalvm image (or similar) would be great

**Comment by tdas** [comment]
@vikrantpuppala is this done? If so can you close it?

**Comment by vikrantpuppala** [comment]
Fixed by #96
