### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by tdas** [unitycatalog/unitycatalog#97]
**Is your feature request related to a problem? Please describe.**

We would like to generate code coverage metrics

**Describe the solution you would like**

- Add code coverage plugin to SBT
- Generate the coverage report
- Somehow make it visible in the PR / build

**Comment by havryliuk** [comment]
@tdas I could pick this up if you don't mind

**Comment by tdas** [comment]
thank you @havryliuk
