### ISSUE TITLE
Refactor and enforce Java style check

### ISSUE THREAD

**Issue by tdas** [unitycatalog/unitycatalog#98]
**Is your feature request related to a problem? Please describe.**

Currently, all the code is not style checked. The styles are added in dev/ but the build by default do not run style check - https://github.com/unitycatalog/unitycatalog/blob/main/build.sbt#L52-L53

**Describe the solution you would like**

We would like to the enable the stylecheck and refactor all the existing code to fit into that style. Since there is a lot of code already, refactoring all of that code in 1 PR is going to be a massive change. So here is my suggested approach to whoever wants to do it 

- Phase 1: Get the javastyle plugin working on the configuration. Currently it is throwing a weird error :( 

- Phase 2: Slowly refactor codes in parts over multiple PRs
      - Run the stylecheck locally to generate all the issues that need to be fixed.
      - Pick one or two directories in the source codes at a time and fix them. Make sure your generated diff is not more than 100-200 lines. This would make the PR much easier to review and quickly merge. But do not enable the style to run automatically. 
      - Keep making such size-bounded PRs until we have fixed all the source codes.

- Phase 3: Enable stylecheck to be run by default.

Multiple folks can pick up different parts of source code and start creating PRs. Before you pick up, comment on this issue to say which modules/projects/directories you are picking, so that others do not

**Comment by nastra** [comment]
From previous experience using Checkstyle in Iceberg and in other projects, the main issue with Checkstyle is that it's difficult for people to (automatically) apply the style being enforced. That's why we switched over to using **spotless** in Iceberg. With **spotless** he respective code format can be enforced and automatically applied (via `./gradle spotlessApply` or via the format action in IntelliJ). 
I'm happy to help out and introduce spotless here if there's interest (I was also the main person that added spotless to the Iceberg project)

**Comment by alcole** [comment]
I have found a fix for the 
[error] (client / checkstyle) java.io.FileNotFoundException: checkstyle-config.xml (No such file or directory)
errors

This enables this to run, but you can another set of errors. I've spent a bit of time on this, but nothing fixed yet. I can submit a pr so at least the config is loading

**Comment by tdas** [comment]
Thank you folks for helping us. 
@nastra I see that there is a spotless sbt plugin - https://github.com/moznion/sbt-spotless . could you give that a spin (I know sbt vs gradle is a paradigm shift :) )
@alcole yeah, `build/sbt client/checkstyle` finds the xml, but then it fails with a weird error `org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true`

**Comment by alcole** [comment]
Hi - I have the checkstyle working now. 
I looked up several other projects usage and although they were scala projects, there was a few hints that I could use and try.

I can see 1535 checkstyle errors - but a lot of these will be easy fixes - like indentation and end of line

I'll prepare a PR for the fix

**Comment by nastra** [comment]
@alcole let's hold off on fixing formatting-related things that checkstyle is bringing up as this might change anyway with spotless. However, other (non-formatting) related checkstyle violations should be ok to fix now

**Comment by alcole** [comment]
yes, ok. I was going to submit so point 1 above is done and we can then approach what it looks like after that

**Comment by alcole** [comment]
Looking at the build.sbt file I think it is already configured to only run over the server and cli. The client and apiDocs are not configured to run the style check here.

All the violations seem to be in this file area: unitycatalog/examples/cli/src/main/java/io/unitycatalog/cli/

**Comment by nastra** [comment]
Just FYI, I've opened https://github.com/unitycatalog/unitycatalog/pull/109 to configure and apply spotless on Java code (still WIP since it requires some documentation updates around how to use spotless)

**Comment by nastra** [comment]
> What I might do next is look at the files that checkstyle was flagging and compare to the actions that javafmtCheckAll has changed

Just FYI that `javafmtCheckAll` doesn't change anything as it only validates that the code adheres to the google-java-format. So what you want to do is actually run `javafmtAll` to automatically apply the code format (that way you don't have to manually go through files and fix them).

**Comment by alcole** [comment]
hi - I've just checked in here again and can see some movement. Looks as though changed have been pushed to correct the cli package. This is still showing some errors with checkstyle though, but not with fmt. This means the style from fmt is now what is being followed here. 
Checkstyle errors can be summarised as relating to import statements - ordering and line breaks and some line being over 100 characters. If you'd like me to look into these futher I can. 

Otherwise I think we should remove the references to checkstyle so there is no risk of conflicting reports - I know where the config for this lives, and can double check documentation as well - let me know and I can do this

**Comment by nastra** [comment]
@alcole yeah it would be great if you could take a look. It would be helpful to figure out which checkstyle rules contradict the code formatting being applied from the *google-java-format*

**Comment by alcole** [comment]
this is the snippet of configuration from checkstyle

        <module name="ImportOrder">
            <property name="separated" value="true"/>
            <property name="ordered" value="true"/>
            <property name="groups" value="java,javax,*,org.opencatalog"/>
            <property name="option" value="under"/>
        </module>

I am unsure why this has been configured in this way, as it was present before v0.1

The google code style looks like this
https://checkstyle.org/checks/imports/importorder.html
-     group of static imports is on the top
-     groups of type imports: "java" and "javax" packages first, then "org" and then all other imports
-     imports will be sorted in the groups
-     groups are separated by, at least, one blank line and aren't separated internally

The main difference is the position of the import statement fmtjava and checkstyle with the current configuration will never agree

Outside of imports (ordering and where spaces are present), the only other errorss flagged by checkstyle are some lines with over 100 characters and a couple of unused imports.

CliParams has lots of configuration that exceed 100 characters in a line, I think as it is textual it is not picked up by javafmt
`
<file name="C:\github\unitycatalog\examples\cli\src\main\java\io\unitycatalog\cli\utils\CliParams.java">
<error line="9" severity="error" message="Line is longer than 100 characters (found 128)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>
<error line="13" severity="error" message="Line is longer than 100 characters (found 197)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>
<error line="22" severity="error" message="Line is longer than 100 characters (found 147)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>
<error line="26" severity="error" message="Line is longer than 100 characters (found 107)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>
<error line="30" severity="error" message="Line is longer than 100 characters (found 335)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>
</file>`

**Comment by alcole** [comment]
Unless there is a good reason for the specific import configureation, based on the above I think we should remove the checkstyle configuration (and any documentation relating to it as well) as this will lead to conflicts.

**Comment by nastra** [comment]
> Unless there is a good reason for the specific import configureation, based on the above I think we should remove the checkstyle configuration (and any documentation relating to it as well) as this will lead to conflicts.

@alcole yes I agree that it's a good idea to remove the checkstyle import configuration since import ordering will be handled by the code formatter

**Comment by alcole** [comment]
When I run checkstyle I get warnings - its been reported already here: https://github.com/etsy/sbt-checkstyle-plugin/issues/35 but that issue has now been open for 2.5+ years

Error is as follows:

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.etsy.sbt.checkstyle.Checkstyle$ (file:/C:/Users/ajcal/AppData/Local/Coursier/Cache/v1/https/repo1.maven.org/maven2/com/etsy/sbt-checkstyle-plugin_2.12_1.0/3.1.1/sbt-checkstyle-plugin-3.1.1.jar)
WARNING: Please consider reporting this to the maintainers of com.etsy.sbt.checkstyle.Checkstyle$



WARNING: System::setSecurityManager will be removed in a future release

@nastra

**Comment by alcole** [comment]
I can work on a fix for 6 of the remaining checkstyle errors I am getting reported so it will align with javafmt

**Comment by alcole** [comment]
As the component parts pass the checkstyle checks, sbt can move on to the next area to check. 
Next is client = (project in file("target/clients/java")) which is showing 1389 checkstyle errors across 56 files. 
then serverModels = (project in file("server") / "target" / "models") 748 errors across 39 files.

I can set up fmt to help here, and then review and tweak based on the checkstyle output after that. The issue may be that this will touch 56 files so any other work in this part of the project will show merge conflicts. What would the preferred approach be in this scenario?

**Comment by nastra** [comment]
Btw `serverModels = (project in file("server") / "target" / "models")` contains generated classes, so you might want to skip running checkstyle on that particular folder/package. The same is true for `client = (project in file("target/clients/java"))`

**Comment by alcole** [comment]
I'll look into turning the checkstyle off for those generated parts
